#!/bin/bash
export SPLUNK_USERNAME="sysadmin"
export SPLUNK_PASSWORD="Changeme1!"

USERS=$(/opt/splunk/bin/splunk list user -auth "${SPLUNK_USERNAME}:${SPLUNK_PASSWORD}" | grep -v "sysadmin" | awk '{print $NF}')

for USER in $USERS; do
    #echo "Removing user: $USER"
    /opt/splunk/bin/splunk remove user $USER -auth "${SPLUNK_USERNAME}:${SPLUNK_PASSWORD}"
done
